### ISSUE TITLE
Changing Data Dir doesn't let the user to get rid of ~/Jackify

### ISSUE THREAD

**Issue by EdualcLaiv** [Omni-guides/Wabbajack-Modlist-Linux#108]
## Bug

When "Jackify Data Dir" is changed is the settings, the default directory is still recreated and populated with about 140MB of data at Jackify's statup.

## How to reproduce

- Go to settings.
- Change Jackify Data Dir to something like `~/JackifyData`.
- Save.
- Close Jackify.
- Delete the default dir (`~/Jackify`).
- Open Jackify again.
- `~/Jackify` has been recreated and populated with files.

## Expected behaviour

Default directories should not be touched again if changed in the settings.

## Note

~~- If a config folder must be created in a fixed place in order to save settings (like where the Data folder should be), it would be more elegant to be stored by default in `~/.config/jackify/`, or in `~/.local/jackify` (or splitted between the two).~~
~~- Hopefully, it should not be filled with so much data if its stored in `/.config`.~~

After checking, it seems the base config file is already en ~/.config/jackify.
My bad.

## Version tested

- Jackify v0.2.0.3
- Jackify v0.2.0.2

(I haven't tried the older ones)

## OS tested on

- Distribution: Omarchy 3.2.3 (based on Arch Linux)
- Kernel: Linux 6.17.9-arch1-1
- Window Manager: Hyprland 0.52.2 (Wayland)

**Comment by Omni-guides** [comment]
Fixed for the next release. Thanks for the report.

**Comment by Omni-guides** [comment]
0.2.0.4 has been released that should resolve this issue.

**Comment by EdualcLaiv** [comment]
I tried the latest release, but it seems the problem is still occurring on my end.

**Comment by Omni-guides** [comment]
Let me take a look...

**Comment by Omni-guides** [comment]
I should have this finally identified - I was mostly running my dev version following removal of hard-coded areas within the code. However, I overlooked that the AppImage itself was set to use ~/Jackify, rather than reading the jackify data dir from the config.json.

I'll include this in the next build.

**Comment by EdualcLaiv** [comment]
By next build, you mean 2.0.6 ? It's still occurring on 2.0.5.

**Comment by Omni-guides** [comment]
Yep, 2.0.6 which isn't released yet.

**Comment by Omni-guides** [comment]
v0.2.0.8 is now out containing the fix for this. 06, 07 and 08 had an underlying bug that caused me to remove them from availability, but the fix should now be in place.

**Comment by EdualcLaiv** [comment]
Yes it's working, the folder is not coming back.


But the default path is still hard coded in strings used to indicate where logs are located:

- `completion_dialog.py`, `_build_completion_text()`, line 201.
- `menu_handler.py`, `run_modlist_configuration_phase()`, line 657.

It's not a big deal but it could be confusing for users not sure where to find said logs.

**Comment by Omni-guides** [comment]
Closing as this should be resolved.
